// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseBlogWorkDir() {
  return window['go']['main']['App']['ChooseBlogWorkDir']();
}

export function ChooseJsonFormatterWorkDir() {
  return window['go']['main']['App']['ChooseJsonFormatterWorkDir']();
}

export function ChooseWorkHourDBPath() {
  return window['go']['main']['App']['ChooseWorkHourDBPath']();
}

export function DeleteBlogFile(arg1) {
  return window['go']['main']['App']['DeleteBlogFile'](arg1);
}

export function EnsureWelcomeBlogFile() {
  return window['go']['main']['App']['EnsureWelcomeBlogFile']();
}

export function GetBlogWorkDir() {
  return window['go']['main']['App']['GetBlogWorkDir']();
}

export function GetDefaultBlogWorkDir() {
  return window['go']['main']['App']['GetDefaultBlogWorkDir']();
}

export function GetDefaultJsonFormatterWorkDir() {
  return window['go']['main']['App']['GetDefaultJsonFormatterWorkDir']();
}

export function GetDefaultWorkHourDBPath() {
  return window['go']['main']['App']['GetDefaultWorkHourDBPath']();
}

export function GetJsonFormatterWorkDir() {
  return window['go']['main']['App']['GetJsonFormatterWorkDir']();
}

export function GetWorkHourDBPath() {
  return window['go']['main']['App']['GetWorkHourDBPath']();
}

export function GetWorkHourRecords() {
  return window['go']['main']['App']['GetWorkHourRecords']();
}

export function ListBlogMarkdownFiles() {
  return window['go']['main']['App']['ListBlogMarkdownFiles']();
}

export function ReadBlogFile(arg1) {
  return window['go']['main']['App']['ReadBlogFile'](arg1);
}

export function ReadJsonFormatterDraft() {
  return window['go']['main']['App']['ReadJsonFormatterDraft']();
}

export function RefreshWorkHourData() {
  return window['go']['main']['App']['RefreshWorkHourData']();
}

export function RenameBlogFile(arg1, arg2) {
  return window['go']['main']['App']['RenameBlogFile'](arg1, arg2);
}

export function SetBlogWorkDir(arg1) {
  return window['go']['main']['App']['SetBlogWorkDir'](arg1);
}

export function SetJsonFormatterWorkDir(arg1) {
  return window['go']['main']['App']['SetJsonFormatterWorkDir'](arg1);
}

export function SetWorkHourDBPath(arg1) {
  return window['go']['main']['App']['SetWorkHourDBPath'](arg1);
}

export function WriteBlogFile(arg1, arg2) {
  return window['go']['main']['App']['WriteBlogFile'](arg1, arg2);
}

export function WriteJsonFormatterDraft(arg1) {
  return window['go']['main']['App']['WriteJsonFormatterDraft'](arg1);
}
