// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AIChatStream(arg1:string,arg2:Array<main.AIChatMessage>):Promise<void>;

export function AddCustomReminder(arg1:string,arg2:string):Promise<string>;

export function ChooseBlogWorkDir():Promise<string>;

export function ChooseJsonFormatterWorkDir():Promise<string>;

export function ChooseReminderDBPath():Promise<string>;

export function ChooseSQLiteDBPath():Promise<string>;

export function ChooseWorkHourDBPath():Promise<string>;

export function DeleteBlogFile(arg1:string):Promise<void>;

export function DeleteCustomReminder(arg1:string,arg2:string,arg3:string):Promise<void>;

export function EnsureWelcomeBlogFile():Promise<void>;

export function GetAISettings():Promise<main.AISettingsView>;

export function GetAboutInfo():Promise<main.AboutView>;

export function GetBlogWorkDir():Promise<string>;

export function GetDefaultBlogWorkDir():Promise<string>;

export function GetDefaultJsonFormatterWorkDir():Promise<string>;

export function GetDefaultReminderDBPath():Promise<string>;

export function GetDefaultWorkHourDBPath():Promise<string>;

export function GetJsonFormatterWorkDir():Promise<string>;

export function GetPullRequestListTotal():Promise<number>;

export function GetReminderDBPath():Promise<string>;

export function GetUITheme():Promise<string>;

export function GetUserSettingsFilePath():Promise<string>;

export function GetWorkHourDBPath():Promise<string>;

export function GetWorkHourRecords():Promise<Array<main.AttendanceRecord>>;

export function GetWorkHourShiftSchedule():Promise<string>;

export function GetWorkHourUserProfile():Promise<main.WorkHourUserProfileView>;

export function ListBlogMarkdownFiles():Promise<Array<string>>;

export function ListCustomReminders():Promise<Array<main.CustomReminder>>;

export function ReadBlogFile(arg1:string):Promise<string>;

export function ReadJsonFormatterDraft():Promise<string>;

export function ReadUserSettingsJSON():Promise<string>;

export function RefreshPullRequestList(arg1:number,arg2:number):Promise<main.PullRequestListResponse>;

export function RefreshWorkHourData():Promise<Array<main.AttendanceRecord>>;

export function RefreshWorkHourUserInfo():Promise<main.WorkHourUserProfileView>;

export function RenameBlogFile(arg1:string,arg2:string):Promise<void>;

export function SQLiteToolDeleteRow(arg1:string,arg2:Record<string, any>):Promise<void>;

export function SQLiteToolDescribeTable(arg1:string):Promise<main.SQLiteTableInfo>;

export function SQLiteToolGetDBPath():Promise<string>;

export function SQLiteToolInsertRow(arg1:string,arg2:Record<string, any>):Promise<void>;

export function SQLiteToolListTables():Promise<Array<string>>;

export function SQLiteToolOpenDB(arg1:string):Promise<void>;

export function SQLiteToolQueryTable(arg1:string,arg2:number,arg3:number):Promise<main.SQLiteQueryResult>;

export function SQLiteToolUpdateRow(arg1:string,arg2:Record<string, any>,arg3:Record<string, any>):Promise<void>;

export function SetAISettings(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetBlogWorkDir(arg1:string):Promise<void>;

export function SetJsonFormatterWorkDir(arg1:string):Promise<void>;

export function SetReminderDBPath(arg1:string):Promise<void>;

export function SetUITheme(arg1:string):Promise<void>;

export function SetWorkHourDBPath(arg1:string):Promise<void>;

export function TerminalResize(arg1:number,arg2:number):Promise<void>;

export function TerminalStart(arg1:string):Promise<void>;

export function TerminalStop():Promise<void>;

export function TerminalWrite(arg1:string):Promise<void>;

export function UpdateCustomReminder(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteBlogFile(arg1:string,arg2:string):Promise<void>;

export function WriteJsonFormatterDraft(arg1:string):Promise<void>;

export function WriteUserSettingsJSON(arg1:string):Promise<void>;
