// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIChatStream(arg1, arg2) {
  return window['go']['main']['App']['AIChatStream'](arg1, arg2);
}

export function AddCustomReminder(arg1, arg2) {
  return window['go']['main']['App']['AddCustomReminder'](arg1, arg2);
}

export function ChooseBlogWorkDir() {
  return window['go']['main']['App']['ChooseBlogWorkDir']();
}

export function ChooseJsonFormatterWorkDir() {
  return window['go']['main']['App']['ChooseJsonFormatterWorkDir']();
}

export function ChooseReminderDBPath() {
  return window['go']['main']['App']['ChooseReminderDBPath']();
}

export function ChooseSQLiteDBPath() {
  return window['go']['main']['App']['ChooseSQLiteDBPath']();
}

export function ChooseWorkHourDBPath() {
  return window['go']['main']['App']['ChooseWorkHourDBPath']();
}

export function DeleteBlogFile(arg1) {
  return window['go']['main']['App']['DeleteBlogFile'](arg1);
}

export function DeleteCustomReminder(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteCustomReminder'](arg1, arg2, arg3);
}

export function EnsureWelcomeBlogFile() {
  return window['go']['main']['App']['EnsureWelcomeBlogFile']();
}

export function GetAISettings() {
  return window['go']['main']['App']['GetAISettings']();
}

export function GetAboutInfo() {
  return window['go']['main']['App']['GetAboutInfo']();
}

export function GetBlogWorkDir() {
  return window['go']['main']['App']['GetBlogWorkDir']();
}

export function GetDefaultBlogWorkDir() {
  return window['go']['main']['App']['GetDefaultBlogWorkDir']();
}

export function GetDefaultJsonFormatterWorkDir() {
  return window['go']['main']['App']['GetDefaultJsonFormatterWorkDir']();
}

export function GetDefaultReminderDBPath() {
  return window['go']['main']['App']['GetDefaultReminderDBPath']();
}

export function GetDefaultWorkHourDBPath() {
  return window['go']['main']['App']['GetDefaultWorkHourDBPath']();
}

export function GetJsonFormatterWorkDir() {
  return window['go']['main']['App']['GetJsonFormatterWorkDir']();
}

export function GetPullRequestListTotal() {
  return window['go']['main']['App']['GetPullRequestListTotal']();
}

export function GetReminderDBPath() {
  return window['go']['main']['App']['GetReminderDBPath']();
}

export function GetUITheme() {
  return window['go']['main']['App']['GetUITheme']();
}

export function GetUserSettingsFilePath() {
  return window['go']['main']['App']['GetUserSettingsFilePath']();
}

export function GetWorkHourDBPath() {
  return window['go']['main']['App']['GetWorkHourDBPath']();
}

export function GetWorkHourRecords() {
  return window['go']['main']['App']['GetWorkHourRecords']();
}

export function GetWorkHourShiftSchedule() {
  return window['go']['main']['App']['GetWorkHourShiftSchedule']();
}

export function GetWorkHourUserProfile() {
  return window['go']['main']['App']['GetWorkHourUserProfile']();
}

export function ListBlogMarkdownFiles() {
  return window['go']['main']['App']['ListBlogMarkdownFiles']();
}

export function ListCustomReminders() {
  return window['go']['main']['App']['ListCustomReminders']();
}

export function ReadBlogFile(arg1) {
  return window['go']['main']['App']['ReadBlogFile'](arg1);
}

export function ReadJsonFormatterDraft() {
  return window['go']['main']['App']['ReadJsonFormatterDraft']();
}

export function ReadUserSettingsJSON() {
  return window['go']['main']['App']['ReadUserSettingsJSON']();
}

export function RefreshPullRequestList(arg1, arg2) {
  return window['go']['main']['App']['RefreshPullRequestList'](arg1, arg2);
}

export function RefreshWorkHourData() {
  return window['go']['main']['App']['RefreshWorkHourData']();
}

export function RefreshWorkHourUserInfo() {
  return window['go']['main']['App']['RefreshWorkHourUserInfo']();
}

export function RenameBlogFile(arg1, arg2) {
  return window['go']['main']['App']['RenameBlogFile'](arg1, arg2);
}

export function SQLiteToolDeleteRow(arg1, arg2) {
  return window['go']['main']['App']['SQLiteToolDeleteRow'](arg1, arg2);
}

export function SQLiteToolDescribeTable(arg1) {
  return window['go']['main']['App']['SQLiteToolDescribeTable'](arg1);
}

export function SQLiteToolGetDBPath() {
  return window['go']['main']['App']['SQLiteToolGetDBPath']();
}

export function SQLiteToolInsertRow(arg1, arg2) {
  return window['go']['main']['App']['SQLiteToolInsertRow'](arg1, arg2);
}

export function SQLiteToolListTables() {
  return window['go']['main']['App']['SQLiteToolListTables']();
}

export function SQLiteToolOpenDB(arg1) {
  return window['go']['main']['App']['SQLiteToolOpenDB'](arg1);
}

export function SQLiteToolQueryTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['SQLiteToolQueryTable'](arg1, arg2, arg3);
}

export function SQLiteToolUpdateRow(arg1, arg2, arg3) {
  return window['go']['main']['App']['SQLiteToolUpdateRow'](arg1, arg2, arg3);
}

export function SetAISettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAISettings'](arg1, arg2, arg3);
}

export function SetBlogWorkDir(arg1) {
  return window['go']['main']['App']['SetBlogWorkDir'](arg1);
}

export function SetJsonFormatterWorkDir(arg1) {
  return window['go']['main']['App']['SetJsonFormatterWorkDir'](arg1);
}

export function SetReminderDBPath(arg1) {
  return window['go']['main']['App']['SetReminderDBPath'](arg1);
}

export function SetUITheme(arg1) {
  return window['go']['main']['App']['SetUITheme'](arg1);
}

export function SetWorkHourDBPath(arg1) {
  return window['go']['main']['App']['SetWorkHourDBPath'](arg1);
}

export function TerminalResize(arg1, arg2) {
  return window['go']['main']['App']['TerminalResize'](arg1, arg2);
}

export function TerminalStart(arg1) {
  return window['go']['main']['App']['TerminalStart'](arg1);
}

export function TerminalStop() {
  return window['go']['main']['App']['TerminalStop']();
}

export function TerminalWrite(arg1) {
  return window['go']['main']['App']['TerminalWrite'](arg1);
}

export function UpdateCustomReminder(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCustomReminder'](arg1, arg2, arg3);
}

export function WriteBlogFile(arg1, arg2) {
  return window['go']['main']['App']['WriteBlogFile'](arg1, arg2);
}

export function WriteJsonFormatterDraft(arg1) {
  return window['go']['main']['App']['WriteJsonFormatterDraft'](arg1);
}

export function WriteUserSettingsJSON(arg1) {
  return window['go']['main']['App']['WriteUserSettingsJSON'](arg1);
}
